name: Build & Push containers
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Registry
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: GitHub Action for Docker
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      run: build -t marekkowalonek/actions-docker-hub-demo src && docker push marekkowalonek/actions-docker-hub-demo
