name: Build & Push containers
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build src/Dockerfile
    #   run: |
    #     echo $DOCKER_USERNAME
    #     echo $DOCKER_PASSWORD
    # - name: Docker Registry
    #   uses: actions/docker/login@master
    #   env: 
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: GitHub Action for Docker
    #   run: |
    #     docker build src 
    #     docker push marekkowalonek/actions-docker-hub-demo