on: push
name: Build and Publish
jobs:
  dockerLint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Build
      uses: actions/docker/cli@master
      with:
        args: build -t heroku .
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Tag
      uses: actions/docker/tag@master
      with:
        args: heroku github/heroku --no-latest
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PREPROD }}
      with:
        args: container:login
    - name: push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PREPROD }}
      with:
        args: container:push -a pre-bridgeit-api web
    - name: release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PREPROD }}
      with:
        args: container:release -a pre-bridgeit-api web
