<<<<<<< HEAD
on: pull_request
name: PREPROD
jobs:
  dockerLint:
    name: Deploy PREPROD to Heroku
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PREPROD }}
      with:
        args: container:login
    - name: push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PREPROD }}
      with:
        args: container:push -a pre-bridgeit-api web
    - name: release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_PREPROD }}
      with:
        args: container:release -a pre-bridgeit-api web
=======
name: PREPROD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: npm install
    - name: run eslint
      run: npm run lint
    
>>>>>>> 22b3210... test
